dist: xenial

language: java

jdk: openjdk11

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "facebook-final-project"
    token: {SONAR_TOKEN}

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


